### ISSUE TITLE
running python manage.py run open python console instead of running server

### ISSUE THREAD

**Issue by keinagae** [hlop3z/fastberry#1]

**Comment by hlop3z** [comment]
Hi, can you please provide me with more information is there anything showing in the shell? Also, some screenshots could help.

**Comment by keinagae** [comment]
nothing it say starting server and tehn it open python shell

**Comment by keinagae** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/43607374/203662811-5ea50637-d266-4566-8925-1be9961c0c49.png">
output

**Comment by hlop3z** [comment]
Hmm that's weird. Can you show me your `pyproject.toml` please. Also try the command `pdm run app run` It shouldn't be the reason but maybe it is.

**Comment by keinagae** [comment]
Ah atm away from my laptop but will send it in couple of hours

**Comment by keinagae** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/43607374/203739232-65f63b2e-9764-4bb2-9053-eaa2dee10363.png">

**Comment by keinagae** [comment]
[project]
name = "todo"
version = "0.01"
description = "haha"
authors = [
    {name = "kai nagae", email = ""},
]
dependencies = [
    "fastberry[testing]>=0.0.66",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]

[tool.pdm.scripts]
app = "python manage.py"

**Comment by keinagae** [comment]
one thing uvicorn main:app  with fast api does work so not sure but with manage.py run it opens python shell

**Comment by hlop3z** [comment]
Thanks, I'm going to see if I can figure it out. You said it works with Uvicorn right? Because if it's working with uvicorn it should work with `manage.py`. That's what the script does it runs uvicorn. But it also starts a script that lints your code on save. Maybe that's what is causing the error.

**Comment by hlop3z** [comment]
![image](https://user-images.githubusercontent.com/23062270/203882468-6a30faf5-2431-494a-9eec-e9df96156a87.jpeg)


[run-script](https://github.com/hlop3z/fastberry/blob/main/src/fastberry/handlers/cmd/run.py)

**Comment by keinagae** [comment]
With uvcorn fastapi loads but gql endpoint was failing

**Comment by hlop3z** [comment]
# Replaced 

```python
shell_command(cmd)
```

# With 

```python
os.system(cmd)
```

And, It looks like it solved the issue.
