### ISSUE TITLE
what should we return from query method as i tried to return response class object received from manager but its failing and same was happening for mutations but it worked by returning response.data any idea what  i am missing or is there an example project?

### ISSUE THREAD

**Issue by keinagae** [hlop3z/fastberry#3]

**Comment by hlop3z** [comment]
There's no example project yet. but that's a good idea! I created a video tutorial and a tutorial. 

- Video: https://youtu.be/6hRUNtD_Ygg
- Tutorial: https://hlop3z.github.io/fastberry/getting-started/

But if your type looks like this.

![image](https://user-images.githubusercontent.com/23062270/204166311-f86a39d4-b263-4253-a4a9-03694e961a19.png)

the return should look something like this.

![image](https://user-images.githubusercontent.com/23062270/204166362-54c2a2e7-337d-40c6-8266-830f93b8591f.png)

**Comment by keinagae** [comment]
So in simple terms we can say manager is more like an orm and types or response types and manager does not transform its queries to types correct?

**Comment by hlop3z** [comment]
Yes, the ORM part "objects" or "manager" is like an ORM. But it's built from the **`type`** you designed. The reason it doesn't automatically converts it back and forth. It's because you may want to **`resolve`** a "`field`" via the field it self or via the whole **object** with the **manager**. And this gives you the developer(s) more control on how you resolve each field or object. 

P.S. I already started working in a example project.

**Comment by keinagae** [comment]
thanks looking forward to it and one thing can we use pydantic as type and same class as form? i have worked with  [tortose-orm](https://tortoise-orm.readthedocs.io/en/latest/) and [beanie](https://github.com/roman-right/beanie) and found these to be pretty good and they sit well with pydantic and with that we might get rid of having to create time but still user can create one if he wants to

**Comment by hlop3z** [comment]
The tool is in part built with **Strawberry**, here you can see how to use [Pydantic-with-Strawberry](https://strawberry.rocks/docs/integrations/pydantic) but it's an "experimental feature". In fact you can decide to not use the database part I built and instead use [Strawberry-Types](https://strawberry.rocks/docs/types/object-types) and then for the database use any tool you prefer. 


[Example-Project](https://github.com/hlop3z/fastberry-todo)
I created an example project. Hopefully it helps! I will try to improve it when I have more free-time.

**Comment by hlop3z** [comment]
> thanks looking forward to it and one thing can we use pydantic as type and same class as form? i have worked with [tortose-orm](https://tortoise-orm.readthedocs.io/en/latest/) and [beanie](https://github.com/roman-right/beanie) and found these to be pretty good and they sit well with pydantic and with that we might get rid of having to create time but still user can create one if he wants to

# Here is a better Project Example
## [fbauth](https://github.com/hlop3z/fbauth)
